### ISSUE TITLE
Uint8 and >2gb models

### ISSUE THREAD

**Issue by harrisonvanderbyl** [MollySophia/rwkv-qualcomm#1]
Can try https://github.com/RWKV/rwkv-onnx for creating onnx graph from scratch without pytorch to facilitate more fine grained control over operators

**Comment by MollySophia** [comment]
Thanks for you suggestion!
Actually I've tried to use your rwkv-onnx as the base.
The reason I eventually didn't pick that was:
- I'm not so familiar with onnx :P
- The QNN SDK doesn't support the ```DynamicQuant``` onnx op

uint8 quant is handled by tools in QNN SDK, while >2gb models don't have problems when using torch==2.2.0

**Comment by MollySophia** [comment]
Thought about this again and I think I may try to take your suggestion.
Thanks again!
