### ISSUE TITLE
QNN转换模型失败问题

### ISSUE THREAD

**Issue by zhaoxuejun1234** [MollySophia/rwkv-qualcomm#10]
大佬，谢谢你今天已经回答了我两个问题了，我真得给你磕一个，都不好意思打扰你了，但我又报错了，呜呜🥹，日志如下，你有空能给看看不？
![image](https://github.com/user-attachments/assets/8de5c91f-d8a2-44ff-8497-bbc332bfecf6)

**Comment by zhaoxuejun1234** [comment]
好像是个setup issue，我再设置设置

**Comment by MollySophia** [comment]
> 好像是个setup issue，我再设置设置

看起来确实是的😂请认真过一遍environment setup：https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-50/linux_setup.html

> 大佬，谢谢你今天已经回答了我两个问题了，我真得给你磕一个，都不好意思打扰你了，但我又报错了，呜呜🥹

没事，有人用我的项目我挺开心的（

**Comment by zhaoxuejun1234** [comment]
大佬，conver_model.py成功转成so了，但有些警告，这些警告你有遇到嘛？
![image](https://github.com/user-attachments/assets/18106b0d-f9b4-4e84-abcb-0e0b92fd8f5c)

**Comment by MollySophia** [comment]
> 大佬，conver_model.py成功转成so了，但有些警告，这些警告你有遇到嘛？ ![image](https://private-user-images.githubusercontent.com/44207679/397338295-18106b0d-f9b4-4e84-abcb-0e0b92fd8f5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MDQzNTEsIm5iZiI6MTczNDYwNDA1MSwicGF0aCI6Ii80NDIwNzY3OS8zOTczMzgyOTUtMTgxMDZiMGQtZjliNC00ZTg0LWFiY2ItMGUwYjkyZmQ4ZjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEwMjczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmODY3NDQ2ZWZkNjljNTIyODA2MWFlZDMyNjliMjEwZmY1OTQ2MzQ5MWZkMzg0YThiMzYwNGRiMDI4MTA2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XbtVlCxZledfFIMsbonIRJR0pFr7qdj2nKC-MurDQhQ)

这些是正常现象，不用在意

**Comment by zhaoxuejun1234** [comment]
秒回，开源榜样啊！

**Comment by MollySophia** [comment]
> 秒回，开源榜样啊！

哈哈哈哈刚好在刷手机
