### ISSUE TITLE
Int8?

### ISSUE THREAD

**Issue by pro9code** [MollySophia/rwkv-qualcomm#2]
Pleassss

**Comment by MollySophia** [comment]
Currently QNN only supports fp16 activation + unquantized weights, or quantized activation + quantized weights.
I’ve already opened a case about fp16+quantized weights and I’m waiting for response from Qualcomm

**Comment by MollySophia** [comment]
A16W8 support for RWKV v6 1.6B, as well as some docs on usage has been added.
