### ISSUE TITLE
Explanation of Argument Specification

### ISSUE THREAD

**Issue by myan-o** [MollySophia/rwkv-qualcomm#3]
There is no explanation of how to specify arguments, so I don't know how to use it.

**Comment by WangHao311** [comment]
@MollySophia Thank for your sharing, but I have the same problem.

**Comment by MollySophia** [comment]
@myan-o @WangHao311 Sorry for the lack of proper documents. The repo was for experimental uses, and I will clean and migrate to make a more easy-to-use one soon

**Comment by MollySophia** [comment]
I've added detailed usage explanation in README.md.
