### ISSUE TITLE
How to test this experiment?

### ISSUE THREAD

**Issue by hmkim97** [MollySophia/rwkv-qualcomm#4]
Hello, thank you for sharing your great work.

I'm interested in developing DNN application on Snapdragon devices (e.g. Xiaomi...)

but i'm first to developing using this qnn(Qualcomm AI Engine Direct SDK), so I am having difficulty developing.

Since I am interested in your development, I would like to try it out myself, but as far as I know, it usually have to connected to a snapdragon device via adb(android debug bridge) and then deploy executable file.

Is the code you provided compiled on a xiaomi 14 device, or is it compiled on a Linux host device and then run remotely via adb?

If you could explain the experimental method in more detail, it would be a better project. Thank you.

**Comment by MollySophia** [comment]
It is compiled on a Linux host device and then run remotely via adb.
The code is basically a modified version of QNN_SDK/examples/QNN/SampleApp, with corresponding rwkv pre/post processings.
You can learn how to use QNN with QNN_SDK/docs/QNN/general/sample_app.html

**Comment by MollySophia** [comment]
I've added detailed usage explanation in README.md. You can check that if still needed
