### ISSUE TITLE
The QNN inference results are very different from the onnxruntime inference results

### ISSUE THREAD

**Issue by MrJungle1** [MollySophia/rwkv-qualcomm#5]
I use QNN to infer the onnx model of DINOv2. Under the same fp32 input, the inference results are very different from the onnxruntime results. The backend used is CPU ([libQnnCpu.so](https://libqnncpu.so/)), both on x86 linux and 8gen3.
Do you know what the reason is?
Here are all my steps.
1.qnn-onnx-converter --input_network dinov2.onnx --input_dim input 1,3,224,224 --out_node output --output_path dinov2_src/dinov2.cpp
2.qnn-model-lib-generator -c dinov2_src/dinov2.cpp -b dinov2_src/dinov2.bin -t x86_64-linux-clang -o dinov2_libs
3.qnn-net-run --backend ../lib/x86_64-linux-clang/[libQnnCpu.so](https://libqnncpu.so/) --input_list input_list.txt --output_dir cpu_out --model dinov2_libs/x86_64-linux-clang/[libdinov2.so](https://libdinov2.so/)
4.Then compare the output of onnxruntime and qnn
![image](https://github.com/user-attachments/assets/8de61adb-8e73-44d4-8f54-e311723f466e)

imageThe model was downloaded from here
https://huggingface.co/sefaburak/dinov2-small-onnx

Just output and generate one randomly

**Comment by MollySophia** [comment]
You can check your input data layout.
QNN may need nhwc instead of nchw, but I'm not sure

**Comment by MrJungle1** [comment]
Thank you for your reply. The following simple model has incorrect accuracy.
![image](https://github.com/user-attachments/assets/694d57e4-83bd-4e4c-b763-a639578658bd)
