### ISSUE TITLE
Rwkv 6 Self Attention' object has no attribute 'online preparing'

### ISSUE THREAD

**Issue by zhaoxuejun1234** [MollySophia/rwkv-qualcomm#8]
I am a rookie on RWKV, when trying the convert_model.py, got Rwkv 6 Self Attention' object has no attribute 'online preparing'. Are there any clues on that?
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/6b0b0dce-7176-49d3-9cbb-f64ae1c1480d" />

**Comment by MollySophia** [comment]
This error seems to be due to me forgetting to push some modifications on my local machine lol. Sorry for that.
Should be fixed with 2a6469b15178ed3c78262c3834f2212380f6e97f.
