### ISSUE TITLE
Questions about the QNN model

### ISSUE THREAD

**Issue by zhaoxuejun1234** [MollySophia/rwkv-qualcomm#9]
![image](https://github.com/user-attachments/assets/a160a2af-2f06-4a21-82ae-5470c6387370)
Thanks for your former answer! It helps a lot! Are these files the QNN binaries needed for inference? Why is the file storage still so large?

**Comment by MollySophia** [comment]
These files might be a bit old now, and may not be useable with current code/newest QNN sdk version. Please ignore these files for now.

> Why is the file storage still so large?

I believe these files were unquantized fp16 models. That's why they are so large
